export const ADD_NEW_TALENT = "ADD_NEW_TALENT";
export const OPEN_MODAL_TALENT = "OPEN_MODAL_TALENT";
export const CLOSE_MODAL_TALENT = "CLOSE_MODAL_TALENT";
export const OPEN_MODAL_ICON = "OPEN_MODAL_ICON";
export const CLOSE_MODAL_ICON = "CLOSE_MODAL_ICON";
export const UPDATE_FORM_ICON = "UPDATE_FORM_ICON";
export const UPDATE_TALENT = "UPDATE_TALENT";